version: "3.7"

services:
  api:
    image: udemy-flask-app
    build:
      context: .
    container_name: flask-store
    volumes:
      - .:/usr/src/app
    ports:
      - 5000:5000
    environment:
      PYTHONUNBUFFERED: 1
      FLASK_ENV: development
      DATABASE_USER: ${POSTGRES_USER}
      DATABASE_PASSWORD: ${POSTGRES_PASSWORD}
      DATABASE_NAME: ${POSTGRES_DB}
      DATABASE_HOST: db
      DATABASE_PORT: 5432

  db:
    image: postgres
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    restart: always

volumes:
  postgres-data:
